title: "Animal Crossing KR Wiki"
description: "한국어 동물의 숲: 뉴 호라이즌 팬 위키"
url: "https://cute-bite.github.io"
baseurl: "/animalcrossing"

theme: null
plugins: []

markdown: kramdown
kramdown:
  input: GFM
